export const gameCharacters = [
    {
        "id": "anemone",
        "name": "Anemone",
        "nickname": "Anemone",
        "G": "F",
        "Love": "TRUE",
        "Age10": "9",
        "Birthday": "dust-1",
        "DialogColor": "FFC6B2",
        "Default BG": "garrison",
        "Basics": "Energetic girl who loves sports.",
        "More": "Stubbornly loyal to her friends and the colony.",
        "Enhancement": "Armor-scaled skin",
        "Fillbar1": "Rebellion, Loyalty, 9",
        "Fillbar2": "Chillness, Energy, 7",
        "Fillbar3": "Goofball, Serious, 1, 5, 9"
    },
    {
        "id": "cal",
        "name": "Recalcitrance",
        "nickname": "Cal",
        "G": "M",
        "Love": "TRUE",
        "Age10": "11",
        "Birthday": "dust-3",
        "DialogColor": "bef7c7",
        "Default BG": "garden",
        "Basics": "Physically strong boy who isn't afraid to get in touch with his emotions.",
        "More": "Pacifist, loves animals.",
        "Enhancement": "Heat/cold tolerant",
        "Fillbar1": "Rebellion, Loyalty, 6",
        "Fillbar2": "Delicate, Tough, 8",
        "Fillbar3": "Peaceful, Angry, 0, 1, 3"
    },
    {
        "id": "tang",
        "name": "Tangent",
        "nickname": "Tangent",
        "G": "F",
        "Love": "TRUE",
        "Age10": "9",
        "Birthday": "wet-3",
        "DialogColor": "EED6FF",
        "Default BG": "colony_quiet",
        "Basics": "Studious and mature girl, often too busy to play with the others.",
        "More": "Devoted to helping the colony thrive via science.",
        "Enhancement": "Reduced sleep",
        "Fillbar1": "Rebellion, Loyalty, 5",
        "Fillbar2": "Humorous, Stoic, 8",
        "Fillbar3": "Intelligent, Silly, 1"
    },
    {
        "id": "dys",
        "name": "Dysthymia",
        "nickname": "Dys",
        "G": "M",
        "Love": "TRUE",
        "Age10": "9",
        "Birthday": "wet-3",
        "DialogColor": "FFDFB7",
        "Default BG": "expeditions",
        "Basics": "Withdrawn boy, a loner and awkward around other people.",
        "More": "Often sneaks away to who knows where.",
        "Enhancement": "No sense of fear",
        "Fillbar1": "Rebellion, Loyalty, 4, 2, 0",
        "Fillbar2": "Adventurous, Homebody, 3, 2, 1",
        "Fillbar3": "Controlled, Wild, 5, 7, 9"
    },
    {
        "id": "marz",
        "name": "Marzipan",
        "nickname": "Marz",
        "G": "F",
        "Love": "TRUE",
        "Age10": "10",
        "Birthday": "wet-1",
        "DialogColor": "C7F0FF",
        "Default BG": "colony",
        "Basics": "Fierce and fiery girl with big dreams of success.",
        "More": "Loves to be in charge so don't get in her way.",
        "Enhancement": "Shameless",
        "Fillbar1": "Rebellion, Loyalty, 3, 4, 5",
        "Fillbar2": "Quiet, Outspoken, 9",
        "Fillbar3": "Socialist, Capitalist, -1"
    },
    {
        "id": "tammy",
        "name": "Aspartame",
        "nickname": "Tammy",
        "G": "F",
        "Love": "TRUE",
        "Age10": "11",
        "Birthday": "pollen-3",
        "DialogColor": "FFF9B2",
        "Default BG": "colony",
        "Basics": "Sweet, down to earth girl who prefers to stay close to home and care for others.",
        "More": "Honest and unselfconscious.",
        "Enhancement": "Enhanced hearing",
        "Fillbar1": "Rebellion, Loyalty, 8",
        "Fillbar2": "Adventurous, Homebody, 10",
        "Fillbar3": "Shy, Confident, -1"
    },
    {
        "id": "rex",
        "name": "Basorexia",
        "nickname": "Rex",
        "G": "M",
        "Love": "TRUE",
        "Age10": "10",
        "Birthday": "pollen-1",
        "DialogColor": "9cffe9",
        "Default BG": "colony",
        "Basics": "Adorable boy from the Heliopause.",
        "More": "More interested in flirting than working, but he's fun to be around.",
        "Enhancement": "Doggy ears",
        "Fillbar1": "Rebellion, Loyalty, 6",
        "Fillbar2": "Chillness, Energy, 5",
        "Fillbar3": "Dog, Boy, 7"
    },
    {
        "id": "nomi",
        "name": "Nomination",
        "nickname": "Nomi-Nomi",
        "G": "X",
        "Love": "TRUE",
        "Age10": "8",
        "Birthday": "dust-2",
        "DialogColor": "F9D6FF",
        "Default BG": "colony",
        "Basics": "Quirky nonbinary kid from the Heliopause.",
        "More": "They never seem to get things right, but their enthusiasm sees them through.",
        "Enhancement": "They don't know",
        "Fillbar1": "Rebellion, Loyalty, 4",
        "Fillbar2": "Quiet, Outspoken, 5",
        "Fillbar3": "Ordinary, Creative, 9"
    },
    {
        "id": "vace",
        "name": "Olivaceous",
        "nickname": "Vace",
        "G": "M",
        "Love": "TRUE",
        "Age10": "13",
        "Birthday": "wet-2",
        "DialogColor": "FFBBC8",
        "Default BG": "garrison",
        "Basics": "Tough, serious older boy from the Heliopause.",
        "More": "Never hesitates to defend others and be the hero.",
        "Enhancement": "Well endowed",
        "Fillbar1": "Rebellion, Loyalty, 8",
        "Fillbar2": "Delicate, Tough, 9",
        "Fillbar3": "Accepting, Controlling, -1"
    },
    {
        "id": "sym",
        "name": "Symbiosis",
        "nickname": "Sym",
        "G": "M",
        "Love": "TRUE",
        "Age10": "",
        "Birthday": "",
        "DialogColor": "FFFFDB",
        "Default BG": "exploreClose",
        "Basics": "Mysterious man who appears when you need him most.",
        "More": "He calls himself a 'Gardener' and is fascinated by humans.",
        "Enhancement": "AI construct",
        "Fillbar1": "Rebellion, Loyalty, 5",
        "Fillbar2": "Humorous, Stoic, 3",
        "Fillbar3": "Human, Alien, 10, 9, 8"
    },
    {
        "id": "Mom",
        "name": "Fluorescent",
        "nickname": "Flulu",
        "G": "F",
        "Love": "",
        "Age10": "43",
        "Birthday": "pollen-3",
        "DialogColor": "",
        "Default BG": "garden",
        "Basics": "Your Mom, the Chief Cultivator. A strong woman up to any challenge, who expects the same from others.",
        "More": "",
        "Enhancement": "",
        "Fillbar1": "",
        "Fillbar2": "",
        "Fillbar3": ""
    },
    {
        "id": "Dad",
        "name": "Geranium",
        "nickname": "Geranium",
        "G": "M",
        "Love": "",
        "Age10": "41",
        "Birthday": "dust-1",
        "DialogColor": "",
        "Default BG": "geoponics",
        "Basics": "Your Dad, who works in geoponics. A kind man, always patient with children and animals.",
        "More": "",
        "Enhancement": "",
        "Fillbar1": "",
        "Fillbar2": "",
        "Fillbar3": ""
    },
    {
        "id": "Eudicot",
        "name": "Eudicot",
        "nickname": "Eudicot",
        "G": "F",
        "Love": "",
        "Age10": "81",
        "Birthday": "dust-3",
        "DialogColor": "",
        "Default BG": "command",
        "Basics": "Governor of your colony, and one of the oldest people in it. Everyone has great respect for her knowledge and leadership.",
        "More": "",
        "Enhancement": "",
        "Fillbar1": "",
        "Fillbar2": "",
        "Fillbar3": ""
    },
    {
        "id": "Lum",
        "name": "Baculum ",
        "nickname": "Lum",
        "G": "M",
        "Love": "",
        "Age10": "25",
        "Birthday": "wet-3",
        "DialogColor": "",
        "Default BG": "bridge",
        "Basics": "Governor after the Heliopause landed. Young, brash and agressive, trained as a soldier but rose in the ranks after the Helio's bridge crew was killed.",
        "More": "",
        "Enhancement": "",
        "Fillbar1": "",
        "Fillbar2": "",
        "Fillbar3": ""
    },
    {
        "id": "Anne",
        "name": "Antecedent",
        "nickname": "Auntie Seedent",
        "G": "F",
        "Love": "",
        "Age10": "36",
        "Birthday": "pollen-3",
        "DialogColor": "",
        "Default BG": "quarters",
        "Basics": "Chief Steward, and everybody's Auntie. She runs the creche and helped raise all the colony children, as well as her own daughter Anemone.",
        "More": "",
        "Enhancement": "",
        "Fillbar1": "",
        "Fillbar2": "",
        "Fillbar3": ""
    },
    {
        "id": "Instance",
        "name": "Instance",
        "nickname": "Instance",
        "G": "F",
        "Love": "",
        "Age10": "50",
        "Birthday": "pollen-1",
        "DialogColor": "",
        "Default BG": "medbay",
        "Basics": "Chief Engineer and ship's medical doctor who is always very busy. You know better than to interrupt her, especially when she's working on her research.",
        "More": "",
        "Enhancement": "",
        "Fillbar1": "",
        "Fillbar2": "",
        "Fillbar3": ""
    },
    {
        "id": "Hal",
        "name": "Halitosis",
        "nickname": "Hal",
        "G": "M",
        "Love": "",
        "Age10": "40",
        "Birthday": "dust-2",
        "DialogColor": "",
        "Default BG": "classroom",
        "Basics": "Your teacher, a cheerful man who loves to tinker and finds joy in learning about every day things.",
        "More": "",
        "Enhancement": "",
        "Fillbar1": "",
        "Fillbar2": "",
        "Fillbar3": ""
    },
    {
        "id": "Tonin",
        "name": "Melatonin",
        "nickname": "Tonin",
        "G": "M",
        "Love": "",
        "Age10": "40",
        "Birthday": "wet-2",
        "DialogColor": "",
        "Default BG": "expeditions",
        "Basics": "Chief Surveyor and ship's pilot, a sweet man who seemed better suited to space than the ground. Tammy's father.",
        "More": "",
        "Enhancement": "",
        "Fillbar1": "",
        "Fillbar2": "",
        "Fillbar3": ""
    },
    {
        "id": "Utopia",
        "name": "Utopia",
        "nickname": "Utopia",
        "G": "F",
        "Love": "",
        "Age10": "22",
        "Birthday": "pollen-2",
        "DialogColor": "",
        "Default BG": "expeditions",
        "Basics": "Young surveyor who loves speeding across the planet on her glider.",
        "More": "The new Chief Surveyor after Uncle Tonin.",
        "Enhancement": "",
        "Fillbar1": "",
        "Fillbar2": "",
        "Fillbar3": ""
    },
    {
        "id": "Rhett",
        "name": "Rhetorical",
        "nickname": "Rhett",
        "G": "M",
        "Love": "",
        "Age10": "50",
        "Birthday": "wet-2",
        "DialogColor": "",
        "Default BG": "garrison",
        "Basics": "Chief of Security, a gruff man who new recruits are frightened by. He takes the colony's safety very seriously.",
        "More": "",
        "Enhancement": "",
        "Fillbar1": "",
        "Fillbar2": "",
        "Fillbar3": ""
    },
    {
        "id": "Congruence",
        "name": "Congruence",
        "nickname": "Congruence",
        "G": "F",
        "Love": "",
        "Age10": "",
        "Birthday": "",
        "DialogColor": "",
        "Default BG": "workshop",
        "Basics": "The ship's artificial intelligence, a vastly powerful computer system which runs everything from life support to the holonet archives. She has a sense of humor, too.",
        "More": "",
        "Enhancement": "",
        "Fillbar1": "",
        "Fillbar2": "",
        "Fillbar3": ""
    },
    {
        "id": "Seeq",
        "name": "Obsequious",
        "nickname": "Seeq ",
        "G": "X",
        "Love": "",
        "Age10": "40",
        "Birthday": "quiet-2",
        "DialogColor": "",
        "Default BG": "command",
        "Basics": "Chief Administrator, a neat and organized individual who keeps the colony running smoothly. They don't like kids very much.",
        "More": "",
        "Enhancement": "",
        "Fillbar1": "",
        "Fillbar2": "",
        "Fillbar3": ""
    },
    {
        "id": "Kom",
        "name": "Kombucha",
        "nickname": "Kom",
        "G": "M",
        "Love": "",
        "Age10": "15",
        "Birthday": "dust-2",
        "DialogColor": "",
        "Default BG": "sportsball",
        "Basics": "Anemone's older brother, a young security officer who coaches sportsball. All the kids love and look up to him.",
        "More": "",
        "Enhancement": "",
        "Fillbar1": "",
        "Fillbar2": "",
        "Fillbar3": ""
    },
    {
        "id": "Nougat",
        "name": "Nougat",
        "nickname": "Nougat",
        "G": "F",
        "Love": "",
        "Age10": "3",
        "Birthday": "dust-3",
        "DialogColor": "",
        "Default BG": "creche",
        "Basics": "Younger child full of barely-controlled energy. She loves games, especially sportsball.",
        "More": "",
        "Enhancement": "",
        "Fillbar1": "",
        "Fillbar2": "",
        "Fillbar3": ""
    },
    {
        "id": "Tirah",
        "name": "Tiramisu",
        "nickname": "Auntie Tirah",
        "G": "F",
        "Love": "",
        "Age10": "34",
        "Birthday": "quiet-3",
        "DialogColor": "",
        "Default BG": "colony",
        "Basics": "Cal's mom, a life support engineer.",
        "More": "",
        "Enhancement": "",
        "Fillbar1": "",
        "Fillbar2": "",
        "Fillbar3": ""
    },
    {
        "id": "Al",
        "name": "Aluminum",
        "nickname": "Al",
        "G": "M",
        "Love": "",
        "Age10": "32",
        "Birthday": "dust-3",
        "DialogColor": "",
        "Default BG": "construction",
        "Basics": "One of Marz's dads, who works in the construction yard.",
        "More": "",
        "Enhancement": "",
        "Fillbar1": "",
        "Fillbar2": "",
        "Fillbar3": ""
    },
    {
        "id": "Bernie",
        "name": "Burnish",
        "nickname": "Bernie",
        "G": "M",
        "Love": "",
        "Age10": "36",
        "Birthday": "wet-1",
        "DialogColor": "",
        "Default BG": "construction",
        "Basics": "One of Marz's dads, who works in the construction yard.",
        "More": "",
        "Enhancement": "",
        "Fillbar1": "",
        "Fillbar2": "",
        "Fillbar3": ""
    }
].sort((a, b) => a.name.localeCompare(b.name))
